spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clients
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8080

logging:
  level:
    root: INFO
